ARG BASE_IMAGE_TAG="8u212-b04-jdk-stretch"
ARG SBT_VERSION="1.3.3" 
ARG SCALA_VERSION="2.13.1" 

FROM mozilla/sbt

WORKDIR /root

ADD . join-backend/

WORKDIR join-backend/

ARG APPLICATION_SECRET
ENV APPLICATION_SECRET ${APPLICATION_SECRET}

ARG JDBC_DATABASE_URL
ENV JDBC_DATABASE_URL ${JDBC_DATABASE_URL}

ARG JDBC_DATABASE_USER
ENV JDBC_DATABASE_USER ${JDBC_DATABASE_USER}

ARG JDBC_DATABASE_PASSWORD
ENV JDBC_DATABASE_PASSWORD ${JDBC_DATABASE_PASSWORD}

ARG ADMIN_URL
ENV ADMIN_URL ${ADMIN_URL}

ARG USER_URL
ENV USER_URL ${USER_URL}

ARG USER_WELCOME_URL
ENV USER_WELCOME_URL ${USER_WELCOME_URL}

ARG AWS_ACCESS_KEY_ID
ENV AWS_ACCESS_KEY_ID ${AWS_ACCESS_KEY_ID}

ARG AWS_SECRET_KEY
ENV AWS_SECRET_KEY ${AWS_SECRET_KEY}

ARG DUMMY_USER_EMAIL
ENV DUMMY_USER_EMAIL ${DUMMY_USER_EMAIL}

ARG DUMMY_USER_PWD
ENV DUMMY_USER_PWD ${DUMMY_USER_PWD}

ARG BRAINTREE_MERCHANT_ID
ENV BRAINTREE_MERCHANT_ID ${BRAINTREE_MERCHANT_ID}

ARG BRAINTREE_PUBLIC_KEY
ENV BRAINTREE_PUBLIC_KEY ${BRAINTREE_PUBLIC_KEY}

ARG BRAINTREE_PRIVATE_KEY
ENV BRAINTREE_PRIVATE_KEY ${BRAINTREE_PRIVATE_KEY}

ARG BRAINTREE_ENVIRONMENT
ENV BRAINTREE_ENVIRONMENT ${BRAINTREE_ENVIRONMENT}

ARG MAILER_HOST
ENV MAILER_HOST ${MAILER_HOST}

ARG MAILER_USER
ENV MAILER_USER ${MAILER_USER}

ARG MAILER_PASS
ENV MAILER_PASS ${MAILER_PASS}

RUN sbt stage

CMD target/universal/stage/bin/sos -Dconfig.resource=env/prod.conf -Dhttp.port=9000 -Dlogger.resource=logback.xml -Dplay.evolutions.db.default.autoApply=true -Dplay.http.secret.key='QCY?tAnfk?aZ?iwrNwnxIlR6CTf:G3gf:90Latabg@5241ABR5W:1uDFN];Ik@n'